---
- name: Verify
  hosts: all

  tasks:
    - name: Collect package facts.
      package_facts:
        manager: "auto"

    - name: Verify mpd is installed.
      assert:
        that:
          - "'mpd' in ansible_facts.packages"
        success_msg: "mpd is installed."
        fail_msg: "mpd is not installed."
